#! /usr/bin/env python
import sys

def fail(msg = ""):
    print(0)
    exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

if len(lines) != 3: fail()

if len(lines[0].split()) != 2: fail("not 2 things on first line")

try:
    n,l = map(int,lines[0].split())
except:
    fail("first line not ints")

if l < 1 or l > 1000000000:fail()
if n < 1 or n > 100000: fail()
if len(lines[1].split()) != n: fail("not n things on second line")
if len(lines[2].split()) != n: fail("not n things on third line")

seen = set()
for i in lines[1].split():
    try:
        i = int(i)
    except:
        fail("thing on line 2 isnt an int")
    if i < 1 or i > l or i%2 == 1 or i in seen: fail("not a valid value on second line")
    seen.add(i)

try:
    p = lines[2].split()
    p = list(map(int,p))
    p.sort()
except:
    fail("couldn't split, map and sort line 3")

for i in range(n):
    if p[i] != i+1: fail("line 3 not a permutation")

print(1)
