#! /usr/bin/env python3
# Sanity for AIO 2019 Evading
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    V, E, X, K = list(map(int, lines[0].split(' ')))
except: fail()

ensure(V, 1, 100000)
ensure(E, 1, 100000)
ensure(X, 1, V)
ensure(K, 1, 1000000000)

try:
    f = lambda x: list(map(int, x.split(' ')))
    edges = list(map(f, lines[1:]))

    g = lambda x: (x[0], x[1]) if x[0] < x[1] else (x[1], x[0])
    edges = list(map(g, edges))
except: fail()

if any(map(lambda x: x[0] == x[1], edges)): fail()

if len(set(edges)) != len(edges): fail()

if len(edges) != E: fail()
    
print(1)
