#! /usr/bin/env python3
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    N,K = map(int,lines[0].split(' '))
except: fail()

ensure(N, 1, 100000)
ensure(K, 1, N)

try:
    xs = list(map(int,lines[1].split(' ')))
    if len(xs) != N: fail()
except: fail()

for i in xs: ensure(i,-10000,10000)

