#!/usr/bin/env python
import sys


def score(s):
    print(s)
    sys.exit()


try:
    studentOut, judgeOut, judgeIn = [open(x) for x in sys.argv[1:4]]

    # Fetch input
    destination = tuple(int(x) for x in judgeIn.readline().split())

    # Fetch output
    judgePath = judgeOut.readline().strip()

    # Fetch and verify student output
    def tupleAdd(a,b):
        return tuple(x+y for x,y in zip(a,b))
    deltas = [(0,1),(1,0),(0,-1),(-1,0)]
    direction = 0
    dChange = {'L':-1, 'R':1}
    location = (0,0)

    studentLines = [x for x in studentOut.readlines() if x.strip()]
    if len(studentLines) != 1:
        score(0)
    stuPath = studentLines[0].strip()
    for c in stuPath:
        if c not in dChange:
            score(0)
        direction = (direction + dChange[c]) % 4
        location = tupleAdd(location, deltas[direction])
    if location == destination and len(stuPath) <= len(judgePath):
        score(100)
    elif location == destination:
        score(50)
    else:
        score(0)
except Exception:
    score(0)
