#! /usr/bin/env python
import sys

def fail():
    print(0)
    exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

if len(lines) != 1: fail()

try:
    x,y = map(int, lines[0].split())
    if x < -5000 or y < -5000 or x > 5000 or y > 5000: fail()
except:
    fail()
print(1)
