TRUNCATE users CASCADE;
TRUNCATE results CASCADE;

INSERT INTO users(username, password, visible, admin) VALUES ('tutors', 'simmeringaioli', FALSE, TRUE);

INSERT INTO users(username, password, visible, admin) VALUES ('ralismark', 'apple$rocks#aio', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('ja_kingy', 'e7822cec', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('anonymous', 'brexitsucks', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('tunanshi', 'f850ac51', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('jamiesonb', 'f5a8e34d', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('jlh', 'b452b7dd', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('1011776', '10123451012345', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('jennivine', '2f53d7d2', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('andrewkerr', 'andrewkerr', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('1015634', 'juju2005', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('bobs_his_face', 'bobeatspotatoes', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('leepiccowoflife', '70fe9912', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('thyroid', 'rjtu99gt', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('brendy', 'b82349ba', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('clancywoo', 'cplusplussucks', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('iiliffe', 'Password5', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('pmoore', 'f560be6a', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('gouren', 'f2e47631', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('pony_joe1', 'Angusage14', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('i_am_sb', 'iamsherlocked', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('mckinleykeys', '393b9dbc', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('mzhao', 'info1234', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('jl58261', 'carrots21', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('super_aiderton', '22scOne\', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('println_hi_', '07ff08be', TRUE, FALSE);
INSERT INTO users(username, password, visible, admin) VALUES ('jojo197', 'Scorpion&', TRUE, FALSE);
