#! /usr/bin/env python3
# Sanity for AIO 2019 RPS
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    N = int(lines[0].strip())
    Ra, Pa, Sa = list(map(int, lines[1].strip().split()))
    Rb, Pb, Sb = list(map(int, lines[2].strip().split()))
except: fail()

ensure(N, 1, 5000)
if Ra + Pa + Sa != Rb + Pb + Sb: fail()
if Ra + Pa + Sa != N: fail()

ensure(N, 1, 100000)
print(1)
