#! /usr/bin/env python3
# Sanity for AIO 2019 RPS
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    A, B, S, C, D = list(map(int, lines[0].strip().split()))
except: fail()

for x in [A, B, S, C, D]:
    ensure(x, 0, 5e8)
if C + D == 0: fail()

print(1)
