#! /usr/bin/env python
import sys

def fail():
    print(0)
    exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

try:
    n,m = map(int, lines[0].split())
except:
    fail()

if n < 2 or n > 100000 or m < 0 or m > n-2:
    fail()

if len(lines) != m+1: fail()

seen = [i < 3 for i in range(n+5)]

for i in range(1,m+1):
    try:
        a,b = map(int,lines[i].split())
        if (not seen[a]) or seen[b]: fail()
        seen[b] = True
    except:
        fail()

print(1)
