#! /usr/bin/env python3
# Sanity for AIO 2019 Hiring
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    N = int(lines[0])
except: fail()

ensure(N, 5, 100000)

S = lines[1]
for x in S:
    if x not in "SNAKE":
        fail()

if N != len(S):
    fail()

print(1)
