#! /usr/bin/env python
import sys

def check(b = False):
    if not b:
        print(0)
        exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

try:
    check(len(lines[0].split()) == 5)
    r,c,k,h,v = map(int,lines[0].split())
except:
    check()

check(len(lines) == 1 + h + v)

check(2 <= r and 2 <= c and r*c <= 2**30)
check(1 <= k and k <= 2**30)
check(0 <= h <= 1500)
check(0 <= v <= 1500)

leftcut = []

for i in range(h):
    try:
        x = int(lines[i+1])
    except:
        check()
    check(1 <= x and x < r)
    leftcut.append(x)

check(leftcut == sorted(leftcut))
check(len(set(leftcut)) == len(leftcut))

bottomcut = []

for i in range(v):
    try:
        x = int(lines[i+h+1])
    except:
        check()
    check(1 <= x and x < c)
    bottomcut.append(x)

check(bottomcut == sorted(bottomcut))
check(len(set(bottomcut)) == len(bottomcut))

print(1)
