#!/usr/bin/env python
import sys

def score(s):
    print(s)
    sys.exit()


try:
    studentOut, judgeOut, judgeIn = [open(x) for x in sys.argv[1:4]]

    # Fetch input
    N, L = (int(x) for x in judgeIn.readline().split())
    positions = [int(x) for x in judgeIn.readline().split()]
    perm = [int(x)-1 for x in judgeIn.readline().split()]

    # Fetch output
    judgeAns = int(judgeOut.readline())

    # Fetch student output
    stuLines = [x for x in studentOut.readlines() if x.strip()]
    if len(stuLines) != 1:
        score(0)
    offset = int(stuLines[0])
    if offset == -1:
        score(100*(judgeAns == -1))

    if offset <= 0 or offset > L:
        score(0)

    positions = [abs(x-offset) for x in positions]

    mapped = [positions[x] for x in perm]

    score(all(mapped[i] <= mapped[i+1] for i in range(N-1))*100)
except Exception:
    score(0)
