#! /usr/bin/env python
import sys

def fail():
    print(0)
    exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

if len(lines) != 4: fail()

try:
    n = int(lines[0])
except:
    fail()

if n < 2 or n > 300000: fail()

for i in range(1,4):
    if len(lines[i]) != n: fail()
    for s in lines[i]:
        if ord(s) < ord('A') or ord(s) > ord('Z'): fail()

print(1)
