#! /usr/bin/env python3
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    N = int(lines[0])
except: fail()

ensure(N, 1, 100000)
if len(lines) != 1+N: fail()

minp = 1

for l in lines[1:]:
    try:
        p,s = map(int,l.split(' '))
    except: fail()

    ensure(p,minp,1000000000)
    ensure(s,0,1000000000)
    minp = p+1

print(1)

