#!/usr/bin/env python3

import json

def problem_gen(ln, sn, d, ic, n):
    o = []
    for i in range(1,n+1):
        o.append({
            "long_name":ln + str(i),
            "short_name":sn + str(i),
            "task_code":"%s/%d.cpp" % (d, i),
            "sanity_exe":"%s/sanity" % (d),
            "broken_exe":"%s/%d.cpp" % (d, i),
            "correct_exe":"%s/correct.cpp" % (d),
            "checker_exe":"%s/checker" % (d) if ic else "match_file"
        })
    return o

problems = []
problems.extend(problem_gen("Panorama ", "a-panorama-", "panorama", False, 3))
problems.extend(problem_gen("Scootchhop ", "b-scootchhop-", "schootchhop", False, 0))
problems.append({
    "long_name": "Scootchhop ST4",
    "short_name": "b-scootchhop-st4",
    "task_code": "scootchhop/1.cpp",
    "sanity_exe": "scootchhop/sanity-st4",
    "broken_exe": "scootchhop/1.cpp",
    "correct_exe": "scootchhop/correct.cpp",
    "checker_exe": "match_file"
})
problems.extend(problem_gen("Coloured Walkway ", "c-colour-", "coloured_walkway", False, 1))
problems.extend(problem_gen("SPOON ", "d-spoon-", "spoon", False, 2))
problems.extend(problem_gen("Statuettes ", "e-statuettes-", "statuettes", False, 1))


with open('problems.json', 'w') as f:
    f.write(json.dumps(problems, indent=4))
