#!/usr/bin/env python3

import json

def problem_gen(ln, sn, d, ic, n):
    o = []
    for i in range(1,n+1):
        o.append({
            "long_name":ln + str(i),
            "short_name":sn + str(i),
            "task_code":"%s/%d.cpp" % (d, i),
            "sanity_exe":"%s/sanity" % (d),
            "broken_exe":"%s/%d.cpp" % (d, i),
            "correct_exe":"%s/correct.cpp" % (d),
            "checker_exe":"%s/checker" % (d) if ic else "match_file"
        })
    return o

problems = []
problems.extend(problem_gen("Construction ", "a-construction-", "construction", False, 4))
problems.extend(problem_gen("Cavalry ", "b-cavalry-", "cavalry", False, 4))
problems.extend(problem_gen("Cloud Cover ", "c-cloud-", "cloud", False, 3))
problems.extend(problem_gen("Janitor ", "d-janitor-", "janitor", False, 3))
problems.extend(problem_gen("Detective ", "e-detective-", "detective", False, 1))
problems.extend(problem_gen("King Arthur II ", "f-arthur-", "arthur", False, 3))


with open('problems.json', 'w') as f:
    f.write(json.dumps(problems, indent=4))
