#!/usr/bin/env python3
import sys
import os

studentOut, judgeOut, judgeIn = [open(x) for x in sys.argv[1:4]]
studentOut = list(filter(lambda x : x != "", studentOut.readlines()))
judgeOut = list(filter(lambda x : x != "", judgeOut.readlines()))
if len(studentOut) != len(judgeOut):
    print(0)
    exit(0)

for i in range(len(studentOut)):
    if studentOut[i].strip() != judgeOut[i].strip():
        print(0)
        exit(0)

print(100)
