#! /usr/bin/env python3
import sys

def fail():
    print(0)
    exit(0)

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    n = int(lines[0])
except: fail()

if n < 1 or n > 100000: fail()
if len(lines) != n+1: fail()

for l in lines[1:]:
    try:
        a = int(l)
    except: fail()
    if a < 1 or a > n: fail()

print(1)
