#! /usr/bin/env python
import sys

def check(b = False):
    if not b:
        print(0)
        exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

try:
    n = int(lines[0])
except:
    check()

check(1 <= n and n <= 100000)

hs = set()

check(len(lines) == n+1)
for i in range(n):
    check(len(lines[i+1].split()) == 4)
    try:
        h, l, r, c = map(int,lines[i+1].split())
    except:
        check()
    check(1 <= h and h <= 1000000)
    check(1 <= l and l <= r and r <= 1000000)
    check(0 <= c and c <= 10000)
    hs.add(h)

check(len(hs) == n)

print(1)
