#!/usr/bin/env python
import sys

studentOut, judgeOut, judgeIn = [open(x) for x in sys.argv[1:4]]
studentOut = studentOut.read().strip()
judgeOut = judgeOut.read().strip()
judgeIn = judgeIn.read().strip()
print(100 if studentOut == judgeOut else 0)
