#! /usr/bin/env python3
# Sanity for Tennis
import sys

def fail():
    print(0)
    sys.exit(0)

def ensure(x, mn, mx):
    if x < mn or x > mx: fail()

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    B, N = list(map(int, lines[0].strip().split()))
    bins = list(map(int, lines[1].strip().split()))

except: fail()

MIN_B = 2;
MAX_B = 1e5;

MIN_N = 1;
MAX_N = 1e9;

MIN_A = 1;
MAX_A = 1e9;

ensure(B, MIN_B, MAX_B)
ensure(N, MIN_N, MAX_N)

if len(bins) != B:
    fail()

for b in bins:
    ensure(b, MIN_A, MAX_A)

CAP = 1e9

ensure(sum(bins), N, CAP)

print(1)
