#! /usr/bin/env python3
import sys

def fail():
    print(0)
    sys.exit(0)

lines = list(filter(lambda l: l != "", [l.strip() for l in sys.stdin.readlines()]))

try:
    l = lines[0].split(' ')
    N = int(l[0])
    M = int(l[1])
except: fail()
if len(l) != 2: fail()
if len(lines) != M+1: fail()

if N < 1 or N > 100000: fail()
if M < 0 or M > 100000: fail()

s = set()

for l in lines[1:]:
    l = l.split(' ')
    if len(l) != 3: fail()
    try:
        a = int(l[0])
        b = int(l[1])
        x = int(l[2])
    except: fail()

    if a < 1 or a > N: fail()
    if b < 1 or b > N: fail()
    if x < 1 or x > 3: fail()
    if a == b: fail()

    s.add((a,b,x))

if len(s) != M: fail()
    
print(1)
