#! /usr/bin/env python
import sys

def fail():
    print(0)
    exit(0)

lines = sys.stdin.readlines()

lines = filter(lambda l: l.strip() != "", lines)
lines = [l.strip() for l in lines]

if len(lines) != 1: fail()

s = lines[0].split(' ')
if len(s) != 4: fail()
for i in s:
    try:
        n = int(i)
        if n < 0 or n > 10000: fail()
    except: fail()

print(1)
